spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:mydb;MODE=MariaDB;DATABASE_TO_LOWER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql
      
  mvc:
    view:
      prefix: classpth:/static/
      suffix: .html
      
mybatis:
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true